esphome:
  name: garage-door
  platform: esp32
  board: esp32-c3-devkitm-1

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional fallback hotspot
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: "khsSD4v$^ff"

# Enable logging for debugging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "4rFXltoIWVgROEHlgGRu9EPhn74Q/K3i/vqC4A+lcWk="

ota:
  - platform: esphome
    password: "73f94c5dbe39ccc2d3262461ab0cbe50"

# Relay Configuration
switch:
  - platform: gpio
    pin: 5
    name: "Garage Door Relay"
    id: relay
    restore_mode: ALWAYS_OFF  # Ensure the relay stays off at startup
    on_turn_on:
      - delay: 1s  # Keep the relay active for 1 second
      - switch.turn_off: relay

# Button Configuration
binary_sensor:
  - platform: gpio
    pin:
      number: 6
      mode: INPUT_PULLUP
      inverted: true
    name: "Garage Door Button"
    on_press:
      - switch.turn_on: relay
